ARG AWS_VERSION
ARG TARGETARCH
ARG BINARY_NAME=action-aws

FROM amazon/aws-cli:${AWS_VERSION}

COPY ${BINARY_NAME}_linux_${TARGETARCH} /usr/local/bin/entrypoint
RUN chmod +x /usr/local/bin/entrypoint

ENTRYPOINT ["/usr/local/bin/entrypoint"]
