[package]
name = "terraform"
version = "0.1.0"
edition = "2021"

[dependencies]
executer = { path = "../core/executer" }
processor = { path = "../core/processor" }
provider = { path = "../core/provider" }
thiserror = "1.0"
async-trait = "0.1"
slog = "2.7"
tokio = { version = "1.0", features = ["full"] }