[tool.poetry]
name = "madpixels-github-actions-tf-plan"
version = "0.0.1"
description = "Terraform plan workflow package"
authors = ["Igor Chelyshkin"]
packages = [
    { include = "tf_plan", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
madpixels-github-actions = { path = "../..", develop = true }  
click = "^8.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
black = "^23.7.0"
isort = "^5.12.0"
mypy = "^1.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tf-plan = "tf_plan.main:main"