[workspace]
resolver = "2"
members = [
    "bin/terraform",

    "hello",
    "pkg/util",
    "pkg/config",
    "pkg/terraform",
    "pkg/core/processor",
    "pkg/core/executer",
    "pkg/core/provider"
]