[workspace]
resolver = "2"
members = [
    "bin/action-terraform",
    "bin/action-aws",

    "pkg/aws",
    "pkg/util",
    "pkg/config",
    "pkg/terraform",
    "pkg/core/processor",
    "pkg/core/executer",
    "pkg/core/provider"
]