name: BuildAndRelease

on:
  push:
    branches: [ "dev1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-musl, aarch64-unknown-linux-musl ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        # Или любой другой способ установить rustup + stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          # Пакеты для x86_64-unknown-linux-musl
          sudo apt-get install -y musl-tools upx
          # И самое главное — кросс-компилятор для aarch64-musl:
          sudo apt-get install -y aarch64-linux-musl-gcc

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }} -p action-terraform
          # Для strip лучше использовать "кросс-strip" или задать RUSTFLAGS='-Clink-arg=-s' 
          # но иногда можно обойтись и встроенным 'strip', если он умеет. 
          # Чтобы быть полностью корректным:
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-musl" ]; then
            aarch64-linux-musl-strip target/aarch64-unknown-linux-musl/release/action-terraform
          else
            strip target/${{ matrix.target }}/release/action-terraform
          fi
          upx --best --lzma target/${{ matrix.target }}/release/action-terraform

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-action-terraform
          path: target/${{ matrix.target }}/release/action-terraform
