name: BuildAndRelease

on:
  push:
    branches: [ "dev1" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Установим cross
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      # Собираем под x86_64-musl
      - name: Build x86_64
        run: cd ./actions && cross build --release --target aarch64-unknown-linux-musl -p action-terraform

      # Собираем под aarch64-musl
      - name: Build aarch64
        run: cd ./actions && cross build --release --target aarch64-unknown-linux-musl -p action-terraform

      # Загрузим артефакты
      - name: Upload x86_64 artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-x86_64
          path: target/x86_64-unknown-linux-musl/release/my_binary

      - name: Upload aarch64 artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-aarch64
          path: target/aarch64-unknown-linux-musl/release/my_binary
