name: BuildAndRelease

on:
  push:
    branches: [ "dev1" ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build x86_64
        run: |
          cd ./actions
          cross build --release --target x86_64-unknown-linux-musl -p action-terraform

      - name: Build aarch64
        run: |
          cd ./actions
          cross build --release --target aarch64-unknown-linux-musl -p action-terraform

      - name: Upload x86_64 artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-x86_64
          path: actions/target/x86_64-unknown-linux-musl/release/action-terraform

      - name: Upload aarch64 artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-aarch64
          path: actions/target/aarch64-unknown-linux-musl/release/action-terraform
