name: CI/CD

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  check:
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-ci.yml@dev
    with:
      working-directory: "./actions"
      binaries: '["terraform", "other-binary"]'
