name: CI/CD

on:
  push:
    branches: [ '**' ]
    tags:
      - 'v*.*.*'
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    branches: [ '**' ]
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  rust-ci:
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-ci.yml@dev
    with:
      working-directory: "./actions"
      binaries-directory: "bin"
      version: ${{ github.ref }}
    secrets:
      PAT: ${{ secrets.PAT }}
