name: CI/CD

on:
  push:
    branches: [ '**' ]
    tags:
      - 'v*.*.*'
    paths:
      - "actions/**.rs"
      - "actions/**/Cargo.toml"
      - "actions/**/Cargo.lock"
  pull_request:
    branches: [ '**' ]
    paths:
      - "actions/**.rs"
      - "actions/**/Cargo.toml"
      - "actions/**/Cargo.lock"

jobs:
  check-pr:
    uses: Mad-Pixels/github-workflows/.github/workflows/check-pr.yml@dev

  rust-ci:
    needs: check-pr
    if: needs.check-pr.outputs.should-run == 'true'
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-ci.yml@dev
    with:
      working-directory: "./actions"
      binaries-directory: "bin"
      version: ${{ github.ref }}
