name: PR Etc

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - main

jobs:
  qa:
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-check.yml@main
    with:
      working-directory: "./actions"
