name: PR Main

on:
  pull_request:
    branches:
      - main
    paths:
      - "actions/**.rs"
      - "actions/**/Cargo.toml"
      - "actions/**/Cargo.lock"

jobs:
  qa:
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-check.yml@dev
    with:
      working-directory: "./actions"
  
  bin:
    needs: qa
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-build.yml@dev
    with:
      working-directory: "./actions"
      crates-path: "bin"
      artifacts: "binaries"
