name: PR main 

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-build.yml@dev
    with:
      working-directory: "./actions"
      binaries: '["terraform", "other-binary"]'
