name: PR Main

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  qa:
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-check.yml@main
    with:
      working-directory: "./actions"
  
  bin:
    needs: qa
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-build.yml@main
    with:
      working-directory: "./actions"
      crates-path: "bin"
