name: Push Terraform

on:
  workflow_dispatch:
    inputs:
      release:
        required: true
        type: string
        description: 'Release version'

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      docker-context: ${{ steps.prepare.outputs.context }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Release Assets
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare Docker Context
        id: prepare
        run: |
          mkdir -p docker-context
          cp images/Dockerfile.terraform docker-context/
          
          for artifact in artifacts/*linux*/*; do
            if [ -f "$artifact" ]; then
              cp "$artifact" docker-context/
            fi
          done
          
          echo "context=docker-context" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: docker-context
          path: docker-context/

  build-and-push:
    needs: prepare
    strategy:
      fail-fast: true
      matrix:
        version: [ "1.5.7", "1.6.0", "1.6.1" ]
    uses: Mad-Pixels/github-workflows/.github/workflows/dockerhub-push.yml@dev
    with: 
      context: docker-context  
      dockerfile: images/Dockerfile.terraform
      repository: "action-terraform"
      tag: ${{ inputs.release }}-${{ matrix.version }}
      build_args: '{"TERRAFORM_VERSION": "${{ matrix.version }}"}'
      platforms: "linux/amd64,linux/arm64"
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}