name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  verify:
    uses: Mad-Pixels/github-workflows/.github/workflows/github-check-tag.yml@main

  bin:
    needs: verify
    if: needs.verify.outputs.is_main == 'true'
    uses: Mad-Pixels/github-workflows/.github/workflows/rust-build.yml@main
    with:
      working-directory: "./actions"
      crates-path: "bin"
  
  publish:
    needs: [verify, bin]
    if: needs.verify.outputs.is_main == 'true'
    uses: Mad-Pixels/github-workflows/.github/workflows/github-release.yml@main
    with:
      tag: ${{ github.ref_name }}
